// Generated by CoffeeScript 1.6.3
#target "aftereffects";
var Aegif, aegif;

Aegif = (function() {
  function Aegif() {}

  Aegif.prototype.render = function() {
    var outputFile;
    outputFile = app.project.renderQueue.items.add(app.project.activeItem);
    app.project.renderQueue.render();
    return this.openInPhotoshop(outputFile);
  };

  Aegif.prototype.openInPhotoshop = function(outputFile) {
    return photoshop.open(new File(outputFile.outputModule(1).file));
  };

  return Aegif;

})();

aegif = new Aegif();

aegif.render();
